---
common-steps: []
version: 2
jobs:
  build:
    docker:
      - image: rust:buster
    steps:
      - checkout
      - setup-docker-engine
      - run:
          command: rm -f target/
      - run:
          command: cargo build
      - run:
          command: ./target/debug/sdstatus -h
workflows:
  version: 2
  sdstatus_ci:
    jobs:
      - build
